apiVersion: v1
kind: Service
metadata:
  name: {{ include "gitops-app.fullname" . }}-go-simple-app
  namespace: {{ .Release.Namespace }}
  labels:
  {{- include "gitops-app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.goSimpleApp.type }}
  selector:
    {{- include "gitops-app.selectorLabels" . | nindent 4 }}
  ports:
  {{- .Values.goSimpleApp.ports | toYaml | nindent 2 }}
