apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitops-app
  namespace: argocd
  finalizers:
    # Ensures `argocd app delete` also removes the deployed resources
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: https://github.com/dmakeroam/gitops-config.git
    targetRevision: main
    path: charts/gitops-app
    helm:
      valueFiles:
        - values.yaml

  destination:
    server: https://kubernetes.default.svc     # this cluster
    namespace: demo

  syncPolicy:
    automated:
      prune: true        # delete resources removed from Git
      selfHeal: true     # revert manual cluster changes
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 3
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 3m
